name: Validate 'setup-xcode'
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read

jobs:
  versions:
    name: ${{ matrix.runner }} / ${{ matrix.xcode-version }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-15, macos-26, macos-27]
        xcode-version: [latest, latest-stable]
        include:
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode
          - runner: macos-15
            xcode-version: '16.2'
          - runner: macos-15
            xcode-version: '16.4'
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-Readme.md#xcode
          - runner: macos-26
            xcode-version: '26.2'
          - runner: macos-26
            xcode-version: '26.3'
          # https://github.com/actions/runner-images/blob/main/images/macos/macos-27-Readme.md#xcode
          # Xcode 27 is currently developer beta only
          - runner: macos-27
            xcode-version: '27.0-beta'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        name: Setup Xcode
        id: setup-xcode
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Print output variables
        run: |
          echo "Version: ${{ steps.setup-xcode.outputs.version }}"
          echo "Path: ${{ steps.setup-xcode.outputs.path }}"